###
GET http://localhost:3002/api/shirts/

###
GET http://localhost:3002/api/shirts/L

###
GET http://localhost:3002/*

###
POST http://localhost:3002/api/shirts/
Content-Type: application/json

{
    "brand": "Nike",
    "model": "model11",
    "size": "XL",
    "price": 19.00
}